### ISSUE TITLE
Button State

### ISSUE THREAD

**Issue by TygoWolven** [rutgerkock/look-and-feel-corporate-identity#1]
In de site staat een knop "_Meer lezen_". Zodra je op deze knop drukt, komt er tekst tevoorschijn. Maar de knop zegt nogsteeds "_Meer lezen_". Zou hier niet "_Minder lezen_" moeten staan?

**Comment by rutgerkock** [comment]
Gefixt!
https://github.com/rutgerkock/look-and-feel-corporate-identity/blob/de6eac4181921c91e3d543b19fb0cc0061c7d9e7/scripts/script.js#L36
